// <auto-generated />
// Migrations/202508061112_CreateUrlTable.cs
using FluentMigrator;

namespace UrlShortener.Api.Data.Migrations;

[Migration(202508061112)]
public sealed class CreateUrlTable : Migration
{
    public override void Up()
    {
        Execute.Sql("CREATE SEQUENCE IF NOT EXISTS urls_id_seq START WITH 1 INCREMENT BY 1;");

        Create.Table("urls")
            .WithColumn("id")
                .AsInt32()
                .PrimaryKey()
                .NotNullable()
            .WithColumn("original_url")
                .AsString(500)
                .NotNullable()
            .WithColumn("short_code")
                .AsString(50)
                .NotNullable()
                .Unique()
            .WithColumn("redirect_count")
                .AsInt32()
                .NotNullable()
                .WithDefaultValue(0)
            .WithColumn("created_at")
                .AsDateTime()
                .NotNullable()
                .WithDefault(SystemMethods.CurrentUTCDateTime);  
    }

    public override void Down()
    {
        Delete.Table("urls");
        Execute.Sql("DROP SEQUENCE IF EXISTS urls_id_seq;");
    }
}
