// <auto-generated />
// Migrations/202508041214_CreateUrlTable.cs
using FluentMigrator;

namespace UrlShortener.Api.Data.Migrations;

[Migration(202508041214)]
public sealed class CreateUrlTable : Migration
{
    public override void Up()
    {
        Create.Table("urls")
            .WithColumn("id")
                .AsInt32()
                .PrimaryKey()
                .Identity()
                .Indexed()
                .Unique()
                .NotNullable()
            .WithColumn("original_url")
                .AsString(500)
                .NotNullable()
            .WithColumn("short_code")
                .AsString(50)
                .NotNullable();
    }

    public override void Down()
    {
        Delete.Table("urls");
    }
}
